# Settings
#baseurl: /class-boilerplate
permalink: pretty

# About
title: Cours Python
tagline: cours Python pour les élèves du collège AR
authors:
  - name: YF - polora
    url: 'http://www.polora.fr/memento'
created: 2017
license:
  name: CC BY-NC-SA
  shortname: CC BY-NC-SA
  url: /LICENSE
  
# Collections
collections:
  addons:
    output: true
    permalink: /:collection/:path:output_ext

kramdown:
  parse_block_html: true
