# Settings

# Setup
title:        Apprendre à programmer en Python
tagline:      Cours de Python pour les élèves du collège AR
baseurl:      ""
paginate:     1
locale:       "fr"

# About/contact
author:
  name:       YF
  url:        http://www.polora.fr/memento 

license:
  name: 	CC BY-NC-SA
  shortname: 	CC BY-NC-SA
  url: 		https://creativecommons.org/
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
